<a href="https://colab.research.google.com/github/Shadoww002/NLP/blob/main/Phase-2/Phase_2_Text_Representations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. OneHot Encoding**

In [27]:
# Step 1: Sentence
sentence = "I love NLP"

# Step 2: Tokenize
words = sentence.split()

# Step 3: Build vocabulary
vocab = list(set(words))

# Step 4: Create index mapping
word_to_index = {word: i for i, word in enumerate(vocab)}

# Step 5: One-hot encoding
one_hot_vectors = {}

for word in words:
    vector = [0] * len(vocab)
    index = word_to_index[word]
    vector[index] = 1
    one_hot_vectors[word] = vector

# Output
for word, vec in one_hot_vectors.items():
    print(word, ":", vec)

I : [1, 0, 0]
love : [0, 0, 1]
NLP : [0, 1, 0]


In [28]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array(["I", "love", "NLP"]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(words)

print(encoded)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


**2. Bag Of Words**

In [34]:
import pandas as pd

data = {
    "sentences": [
        "I love NLP",
        "I love coding",
        "NLP is fun",
        "coding is fun",
        "I enjoy learning NLP",
        "coding makes life easy",
        "learning new things is fun",
        "I love machine learning",
        "NLP and machine learning are powerful",
        "coding and NLP go hand in hand"
    ]
}

df = pd.DataFrame(data)
print(df)

                               sentences
0                             I love NLP
1                          I love coding
2                             NLP is fun
3                          coding is fun
4                   I enjoy learning NLP
5                 coding makes life easy
6             learning new things is fun
7                I love machine learning
8  NLP and machine learning are powerful
9         coding and NLP go hand in hand


In [35]:
df

,sentences
0,I love NLP
1,I love coding
2,NLP is fun
3,coding is fun
4,I enjoy learning NLP
5,coding makes life easy
6,learning new things is fun
7,I love machine learning
8,NLP and machine learning are powerful
9,coding and NLP go hand in hand


In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [36]:
bow = cv.fit_transform(df["sentences"])

In [37]:
cv.vocabulary_

{'love': 12,
 'nlp': 16,
 'coding': 2,
 'is': 9,
 'fun': 5,
 'enjoy': 4,
 'learning': 10,
 'makes': 14,
 'life': 11,
 'easy': 3,
 'new': 15,
 'things': 18,
 'machine': 13,
 'and': 0,
 'are': 1,
 'powerful': 17,
 'go': 6,
 'hand': 7,
 'in': 8}

In [38]:
print(bow[0].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]]


In [39]:
print(bow[1].toarray())

[[0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]]


In [40]:
print(bow[2].toarray())

[[0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0]]


In [41]:
cv.transform(["NLP love sanjay"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]])

**3.N-Grams**

In [42]:
df

,sentences
0,I love NLP
1,I love coding
2,NLP is fun
3,coding is fun
4,I enjoy learning NLP
5,coding makes life easy
6,learning new things is fun
7,I love machine learning
8,NLP and machine learning are powerful
9,coding and NLP go hand in hand


In [43]:
df["sentences"]

,sentences
0,I love NLP
1,I love coding
2,NLP is fun
3,coding is fun
4,I enjoy learning NLP
5,coding makes life easy
6,learning new things is fun
7,I love machine learning
8,NLP and machine learning are powerful
9,coding and NLP go hand in hand


In [44]:
from sklearn.feature_extraction.text import CountVectorizer


In [45]:
cv1 = CountVectorizer(ngram_range=(2,2))
bow = cv1.fit_transform(df["sentences"])
print(cv1.vocabulary_)

{'love nlp': 17, 'love coding': 15, 'nlp is': 23, 'is fun': 10, 'coding is': 4, 'enjoy learning': 6, 'learning nlp': 13, 'coding makes': 5, 'makes life': 19, 'life easy': 14, 'learning new': 12, 'new things': 20, 'things is': 24, 'love machine': 16, 'machine learning': 18, 'nlp and': 21, 'and machine': 0, 'learning are': 11, 'are powerful': 2, 'coding and': 3, 'and nlp': 1, 'nlp go': 22, 'go hand': 7, 'hand in': 8, 'in hand': 9}


In [46]:
cv2 = CountVectorizer(ngram_range=(1,2))
bow = cv2.fit_transform(df["sentences"])
print(cv2.vocabulary_)

{'love': 27, 'nlp': 37, 'love nlp': 30, 'coding': 5, 'love coding': 28, 'is': 19, 'fun': 12, 'nlp is': 40, 'is fun': 20, 'coding is': 7, 'enjoy': 10, 'learning': 21, 'enjoy learning': 11, 'learning nlp': 24, 'makes': 33, 'life': 25, 'easy': 9, 'coding makes': 8, 'makes life': 34, 'life easy': 26, 'new': 35, 'things': 42, 'learning new': 23, 'new things': 36, 'things is': 43, 'machine': 31, 'love machine': 29, 'machine learning': 32, 'and': 0, 'are': 3, 'powerful': 41, 'nlp and': 38, 'and machine': 1, 'learning are': 22, 'are powerful': 4, 'go': 13, 'hand': 15, 'in': 17, 'coding and': 6, 'and nlp': 2, 'nlp go': 39, 'go hand': 14, 'hand in': 16, 'in hand': 18}


In [47]:
cv3 = CountVectorizer(ngram_range=(1,3))
bow = cv3.fit_transform(df["sentences"])
print(cv3.vocabulary_)

{'love': 37, 'nlp': 51, 'love nlp': 41, 'coding': 7, 'love coding': 38, 'is': 27, 'fun': 18, 'nlp is': 56, 'is fun': 28, 'nlp is fun': 57, 'coding is': 10, 'coding is fun': 11, 'enjoy': 15, 'learning': 29, 'enjoy learning': 16, 'learning nlp': 34, 'enjoy learning nlp': 17, 'makes': 45, 'life': 35, 'easy': 14, 'coding makes': 12, 'makes life': 46, 'life easy': 36, 'coding makes life': 13, 'makes life easy': 47, 'new': 48, 'things': 59, 'learning new': 32, 'new things': 49, 'things is': 60, 'learning new things': 33, 'new things is': 50, 'things is fun': 61, 'machine': 42, 'love machine': 39, 'machine learning': 43, 'love machine learning': 40, 'and': 0, 'are': 5, 'powerful': 58, 'nlp and': 52, 'and machine': 1, 'learning are': 30, 'are powerful': 6, 'nlp and machine': 53, 'and machine learning': 2, 'machine learning are': 44, 'learning are powerful': 31, 'go': 19, 'hand': 22, 'in': 25, 'coding and': 8, 'and nlp': 3, 'nlp go': 54, 'go hand': 20, 'hand in': 23, 'in hand': 26, 'coding and 

**4. Tf-IDF**

In [48]:
df

,sentences
0,I love NLP
1,I love coding
2,NLP is fun
3,coding is fun
4,I enjoy learning NLP
5,coding makes life easy
6,learning new things is fun
7,I love machine learning
8,NLP and machine learning are powerful
9,coding and NLP go hand in hand


In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [53]:
tfidf.fit_transform(df["sentences"]).toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.78146442, 0.        , 0.        ,
       0.        , 0.6239498 , 0.        , 0.        ])

In [56]:
tfidf.idf_ ,tfidf.get_feature_names_out()

(array([2.29928298, 2.70474809, 1.78845736, 2.70474809, 2.70474809,
        2.01160091, 2.70474809, 2.70474809, 2.70474809, 2.01160091,
        1.78845736, 2.70474809, 2.01160091, 2.29928298, 2.70474809,
        2.70474809, 1.6061358 , 2.70474809, 2.70474809]),
 array(['and', 'are', 'coding', 'easy', 'enjoy', 'fun', 'go', 'hand', 'in',
        'is', 'learning', 'life', 'love', 'machine', 'makes', 'new', 'nlp',
        'powerful', 'things'], dtype=object))

**Assignment**

In [83]:
from google.colab import files
files.upload()

import os
os.makedirs('/root/.kaggle', exist_ok=True)
!mv kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!pip install kaggle

!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews --unzip

import pandas as pd
df = pd.read_csv("IMDB Dataset.csv")

print(df.shape)
df.head()

Saving kaggle (2).json to kaggle (2) (2).json
mv: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
100% 25.7M/25.7M [00:00<00:00, 193MB/s]

(50000, 2)


,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [84]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [85]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary

import re

def remove_html(text):
    return re.sub(r'<.*?>', '', text)

df['review'] = df['review'].apply(remove_html)
df['review']

,review
0,One of the other reviewers has mentioned that ...
1,A wonderful little production. The filming tec...
2,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is..."
...,...
49995,I thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di..."
49997,I am a Catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...


In [86]:
df['review'] = df['review'].str.lower()
df['review']

,review
0,one of the other reviewers has mentioned that ...
1,a wonderful little production. the filming tec...
2,i thought this was a wonderful way to spend ti...
3,basically there's a family where a little boy ...
4,"petter mattei's ""love in the time of money"" is..."
...,...
49995,i thought this movie did a down right good job...
49996,"bad plot, bad dialogue, bad acting, idiotic di..."
49997,i am a catholic taught in parochial elementary...
49998,i'm going to have to disagree with the previou...


In [87]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['review'] = df['review'].apply(remove_punctuation)
df['review']

,review
0,one of the other reviewers has mentioned that ...
1,a wonderful little production the filming tech...
2,i thought this was a wonderful way to spend ti...
3,basically theres a family where a little boy j...
4,petter matteis love in the time of money is a ...
...,...
49995,i thought this movie did a down right good job...
49996,bad plot bad dialogue bad acting idiotic direc...
49997,i am a catholic taught in parochial elementary...
49998,im going to have to disagree with the previous...


In [88]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

df['tokens'] = df['review'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [89]:
df['tokens']

,tokens
0,"[one, of, the, other, reviewers, has, mentione..."
1,"[a, wonderful, little, production, the, filmin..."
2,"[i, thought, this, was, a, wonderful, way, to,..."
3,"[basically, theres, a, family, where, a, littl..."
4,"[petter, matteis, love, in, the, time, of, mon..."
...,...
49995,"[i, thought, this, movie, did, a, down, right,..."
49996,"[bad, plot, bad, dialogue, bad, acting, idioti..."
49997,"[i, am, a, catholic, taught, in, parochial, el..."
49998,"[im, going, to, have, to, disagree, with, the,..."


In [90]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

df['tokens'] = df['tokens'].apply(
    lambda words: [lemmatizer.lemmatize(w) for w in words]
)
df['clean_review'] = df['tokens'].apply(lambda x: " ".join(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [91]:
df.head()

,review,sentiment,tokens,clean_review
0,one of the other reviewers has mentioned that ...,positive,"[one, of, the, other, reviewer, ha, mentioned,...",one of the other reviewer ha mentioned that af...
1,a wonderful little production the filming tech...,positive,"[a, wonderful, little, production, the, filmin...",a wonderful little production the filming tech...
2,i thought this was a wonderful way to spend ti...,positive,"[i, thought, this, wa, a, wonderful, way, to, ...",i thought this wa a wonderful way to spend tim...
3,basically theres a family where a little boy j...,negative,"[basically, there, a, family, where, a, little...",basically there a family where a little boy ja...
4,petter matteis love in the time of money is a ...,positive,"[petter, matteis, love, in, the, time, of, mon...",petter matteis love in the time of money is a ...


In [92]:
df['sentiment'] = df['sentiment'].str.strip().str.lower()

In [93]:
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

df.head()

,review,sentiment,tokens,clean_review
0,one of the other reviewers has mentioned that ...,1,"[one, of, the, other, reviewer, ha, mentioned,...",one of the other reviewer ha mentioned that af...
1,a wonderful little production the filming tech...,1,"[a, wonderful, little, production, the, filmin...",a wonderful little production the filming tech...
2,i thought this was a wonderful way to spend ti...,1,"[i, thought, this, wa, a, wonderful, way, to, ...",i thought this wa a wonderful way to spend tim...
3,basically theres a family where a little boy j...,0,"[basically, there, a, family, where, a, little...",basically there a family where a little boy ja...
4,petter matteis love in the time of money is a ...,1,"[petter, matteis, love, in, the, time, of, mon...",petter matteis love in the time of money is a ...


In [94]:
df.isnull().sum()

,0
review,0
sentiment,0
tokens,0
clean_review,0


In [ ]:
# Problem 3

# Apply One Hot Encoding
# Step 1: Sentence
sentence = "I love NLP"

# Step 2: Tokenize
words = sentence.split()

# Step 3: Build vocabulary
vocab = list(set(words))

# Step 4: Create index mapping
word_to_index = {word: i for i, word in enumerate(vocab)}

# Step 5: One-hot encoding
one_hot_vectors = {}

for word in words:
    vector = [0] * len(vocab)
    index = word_to_index[word]
    vector[index] = 1
    one_hot_vectors[word] = vector

# Output
for word, vec in one_hot_vectors.items():
    print(word, ":", vec)



In [ ]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [ ]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [ ]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.